// project/ai_fullstack/router-demo/advanced-router/src/App.jsx
import{
  BrowserRouter,
  HashRouter,
  Link,
  Routes,
  Route
} from 'react-router-dom';
import Home from './pages/Home';
import About from './pages/About';

export default function App(){
  return(
    <HashRouter>
      <nav>
        <ul>
          <li><Link to="#/">Home</Link></li>
          <li><Link to="#/about">About</Link></li>
        </ul>
      </nav>
      <Routes path="/" element={<Home />}></Routes>
      <Routes path="/about" element={<About />}></Routes>
    </HashRouter>
  )
}

// vue/all_vue/all_vue/src/App.vue
<script setup>

</script>

<template>
  <div>
  <header>
    <nav>
      <ul>
        <!-- app.use(router)之后 vue-router 带给我们的全局组件 -->
        <li><router-link to="/">Home</router-link></li>
        <li><router-link to="/about">About</router-link></li>
      </ul>
    </nav>
  </header>
  <main>
    <!-- 多个页面的占位符 -->
    <router-view></router-view>
  </main>
  <footer>
  </footer>
</div>
</template>
